import {
  NEW_PICTURE_POST_URL,
  PICTURES_LIST_GET_URL
} from './network';
import {
  SCALE_SETTINGS,
  DEFAULT_SCALE,
  MAX_HASHTAGS_IN_INPUT,
  MAX_COMMENT_LENGTH
} from './new-picture-form';
import { PRISTINE_CONFIG } from './pristine';

const URLS = {
  NEW_PICTURE_POST_URL,
  PICTURES_LIST_GET_URL
};

const NEW_PICTURE_FORM_SETTINGS = {
  SCALE_SETTINGS,
  DEFAULT_SCALE,
  MAX_HASHTAGS_IN_INPUT,
  MAX_COMMENT_LENGTH
};

export {
  URLS,
  NEW_PICTURE_FORM_SETTINGS,
  PRISTINE_CONFIG
};
